import { Link, Navigate, Route, Routes, useParams } from 'react-router-dom';
import { Sidebar } from '../components/Sidebar';
import { ProgressPanel } from '../components/ProgressPanel';
import { lessons, findLesson } from '../data/lessons';
import { Sandbox } from '../features/sandbox/Sandbox';
import { Quiz } from '../features/quiz/Quiz';

function Home(){return <main><section className="hero"><div className="content"><h1>Learn Finance the Interactive Way</h1><p>FinSchool is the W3Schools of Finance: simple lessons, live practice, quizzes, and real-world modeling.</p><input className="search" aria-label="Search lessons" placeholder="Search lessons, formulas, interview questions..."/><p><Link className="button" to="/lessons/what-is-finance">Continue Learning</Link></p></div></section><div className="content grid"><h2>Popular Tutorials</h2>{lessons.slice(0,6).map(l=><Link className="card" to={`/lessons/${l.slug}`} key={l.slug}><strong>{l.title}</strong><p className="small">{l.module} • {l.estimatedTime}</p></Link>)}<h2>Learning Paths</h2><div className="card">Finance Roadmap → Statements → Modeling → Valuation → Interviews</div><h2>Featured Playground</h2><div className="card">Income Statement Builder with editable assumptions and live recalculation.</div><h2>Recent Lessons</h2>{lessons.slice(6,10).map(l=><Link to={`/lessons/${l.slug}`} key={l.slug}>{l.title}</Link>)}</div></main>}

function LessonPage(){const {slug}=useParams();const lesson=slug?findLesson(slug):undefined;if(!lesson)return <Navigate to="/lessons/what-is-finance"/>;return <div className="app-shell"><Sidebar/><main className="content"><p className="caption">{lesson.module}</p><h1>{lesson.title}</h1><p className="small">Estimated time: {lesson.estimatedTime}</p><h3>Prerequisites</h3><ul>{lesson.prerequisites.map(x=><li key={x}>{x}</li>)}</ul><h3>Learning Objectives</h3><ul>{lesson.objectives.map(x=><li key={x}>{x}</li>)}</ul><h3>Simple Explanation</h3><p>{lesson.explanation}</p><h3>Visual Diagram</h3><div className="card">{lesson.diagram}</div><h3>Formula</h3><pre className="card">{lesson.formula}</pre><h3>Step-by-Step Example</h3><p>{lesson.example}</p><h3>Real Company Example</h3><p>{lesson.companyExample}</p><h3>Excel Example</h3><p>{lesson.excelExample}</p><Sandbox seed={lesson.sandbox}/><h3>Common Mistakes</h3><ul>{lesson.mistakes.map(x=><li key={x}>{x}</li>)}</ul><h3>Interview Questions</h3><ul>{lesson.interviewQuestions.map(x=><li key={x}>{x}</li>)}</ul><h3>Practice Questions</h3><ul>{lesson.practiceQuestions.map(x=><li key={x}>{x}</li>)}</ul><Quiz questions={lesson.quiz}/><h3>Key Takeaways</h3><ul>{lesson.takeaways.map(x=><li key={x}>{x}</li>)}</ul>{lesson.nextLesson&&<Link className="button" to={`/lessons/${lesson.nextLesson}`}>Next Lesson</Link>}</main><ProgressPanel lesson={lesson}/></div>}

export function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/lessons/:slug" element={<LessonPage/>}/></Routes>}
